function fig_hdl = Datos_entrada_build
% DATOS_ENTRADA_BUILD
%-------------------------------------------------------------------------------
% File name   : Datos_entrada_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figure1;
% Variables
handles.granulado=getappdata(0,'Granulado');
%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figure1 = figure( ...
			'Tag', 'figure1', ...
			'Units', 'characters', ...
			'Position', [25.4 0.923076923076923 241 48], ...
			'Name', 'Datos_entrada', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
            'Color', [0.4 0.6 1]);

		% --- PANELS -------------------------------------
        
         handles.aplicacion_panel = uipanel( ...
            'Parent', handles.figure1, ...
            'Tag', 'aplicacion_panel', ...
            'Units', 'characters', ...
            'Position', [15 15 44 20], ...
            'Title', 'Aplicaciones', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
            'TitlePosition', 'Centertop');
        
        % MCIA PANELS--------------------------------------
        
		handles.panel_motor_MCIA = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_motor_MCIA', ...
			'Units', 'characters', ...
			'Position', [78 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'MCIA', ...
            'TitlePosition', 'Centertop');

		handles.panel_funcionamiento_MCIA = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_funcionamiento_MCIA', ...
			'Units', 'characters', ...
			'Position', [147.4 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones de funcionamiento', ...
            'TitlePosition', 'Centertop');

		handles.panel_ambiente_MCIA = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_ambiente_MCIA', ...
			'Units', 'characters', ...
			'Position', [78 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones ambientales', ...
            'TitlePosition', 'Centertop');

		handles.panel_combustible_MCIA = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_combustible_MCIA', ...
			'Units', 'characters', ...
			'Position', [147.4 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Combustible', ...
            'TitlePosition', 'Centertop');
        
        % QUEMADOR PANELS---------------------------------------
        
        handles.panel_quemador = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_quemador', ...
			'Units', 'characters', ...
			'Position', [78 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Quemador', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_funcionamiento_quemador = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_funcionamiento_quemador', ...
			'Units', 'characters', ...
			'Position', [147.4 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones de funcionamiento', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_ambiente_quemador = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_ambiente_quemador', ...
			'Units', 'characters', ...
			'Position', [78 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones ambientales', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_combustible_quemador = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_combustible_quemador', ...
			'Units', 'characters', ...
			'Position', [147.4 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Combustible', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');
        
        % CALDERA PANELS----------------------------------------
        
        handles.panel_caldera = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_caldera', ...
			'Units', 'characters', ...
			'Position', [78 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Caldera', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_funcionamiento_caldera = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_funcionamiento_caldera', ...
			'Units', 'characters', ...
			'Position', [147.4 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones de funcionamiento', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_ambiente_caldera = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_ambiente_caldera', ...
			'Units', 'characters', ...
			'Position', [78 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones ambientales', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_combustible_caldera = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_combustible_caldera', ...
			'Units', 'characters', ...
			'Position', [147.4 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Combustible', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');
        
        % TURBINA GAS PANELS------------------------------------
        
        handles.panel_turbina = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_turbina', ...
			'Units', 'characters', ...
			'Position', [78 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Turbina de gas', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_funcionamiento_turbina = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_funcionamiento_turbina', ...
			'Units', 'characters', ...
			'Position', [147.4 25.5 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones de funcionamiento', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_ambiente_turbina = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_ambiente_turbina', ...
			'Units', 'characters', ...
			'Position', [78 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Condiciones ambientales', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		handles.panel_combustible_turbina = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_combustible_turbina', ...
			'Units', 'characters', ...
			'Position', [147.4 9 63.4 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Combustible', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');
        
        % OTRO ESTUDIO PANELS--------------------------------------
        
        handles.panel_otro = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'panel_otro', ...
			'Units', 'characters', ...
			'Position', [78 17.5 132.8 15.4615384615385], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
			'Title', 'Otro estudio', ...
            'visible', 'off', ...
            'TitlePosition', 'Centertop');

		% --- STATIC TEXTS -------------------------------------
        handles.titulo_datos_entrada_texto = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'titulo_datos_entrada_texto', ...
			'Style', 'text', ...
			'Units', 'characters', ...
            'Position', [100 41 31.6 6], ...
            'FontSize', 15, ...
            'FontName', 'Candara', ...
            'Backgroundcolor', [0.4 0.6 1], ...
            'Foregroundcolor', [1 1 1],...
            'String', 'DATOS DE ENTRADA');
        
        % MCIA STATIC TEXTS--------------------------------------
        
		handles.tipo_motor_texto = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'tipo_motor_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 11.4 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');

		handles.carrera_motor_texto = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'carrera_motor_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 8.5 20.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Carrera [mm]');

		handles.diametro_motor_texto = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'diametro_motor_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 5.5 20.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Diámetro[mm]');

		handles.presion_motor_texto = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'presion_motor_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 1 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'p inyección';'[bar]'});

		handles.n_revoluciones_texto = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'n_revoluciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.4 9.4692307692308 22.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Régimen giro';'[rpm]'});

		handles.par_motor_texto = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'par_motor_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.4 6.42307692307692 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Par [Nm]');

		handles.EGR_texto = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'EGR_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.4 2.65384615384615 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'EGR [%]');

		handles.temperatura_ambiente_texto = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'temperatura_ambiente_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'T [ºC]');

		handles.presion_ambiente_texto = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'presion_ambiente_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'p [bar]');

		handles.humedad_relativa_ambiente_texto = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'humedad_relativa_ambiente_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Humedad';'relativa [%]'});
        
        handles.tipo_combustible_texto = uicontrol( ...
			'Parent', handles.panel_combustible_MCIA, ...
			'Tag', 'tipo_combustible_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 9.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');
        
        handles.empresa_combustible_texto = uicontrol( ...
			'Parent', handles.panel_combustible_MCIA, ...
			'Tag', 'empresa_combustible_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 5.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Empresa');
        
        % QUEMADOR STATIC TEXTS--------------------------------
        
        handles.tipo_texto_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'tipo_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');

		handles.altura_llama_texto_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'altura_llama_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 6 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Altura';'llama [mm]'});

		handles.diametro_llama_texto_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'diametro_llama_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Diámetro';'llama [mm]'});
        
       handles.oxidante_texto_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'oxidante_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Oxidante');

		handles.dosado_texto_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'dosado_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Dosado');

		handles.caudal_texto_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'caudal_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Caudal oxid.';'[m3/s]'});
        
        handles.temperatura_ambiente_texto_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'temperatura_ambiente_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'T [ºC]');

		handles.presion_ambiente_texto_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'presion_ambiente_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'p [bar]');

		handles.humedad_relativa_ambiente_texto_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'humedad_relativa_ambiente_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Humedad';'relativa [%]'});
        
        handles.tipo_combustible_texto_quemador = uicontrol( ...
			'Parent', handles.panel_combustible_quemador, ...
			'Tag', 'tipo_combustible_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 9.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');
        
        handles.empresa_combustible_texto_quemador = uicontrol( ...
			'Parent', handles.panel_combustible_quemador, ...
			'Tag', 'empresa_combustible_texto_quemador', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 5.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Empresa');
     
        % CALDERA STATIC TEXTS---------------------------------
        
        handles.tipo_texto_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'tipo_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');

		handles.altura_llama_texto_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'altura_llama_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 6 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Altura';'llama [mm]'});

		handles.diametro_llama_texto_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'diametro_llama_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Diámetro';'llama [mm]'});
        
        handles.dosado_texto_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'dosado_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Dosado');
        
        handles.egr_texto_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'EGR_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'EGR [%]');

		handles.caudal_texto_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'caudal_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Caudal aire';'[m3/s]'});
        
        handles.temperatura_ambiente_texto_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'temperatura_ambiente_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'T [ºC]');

		handles.presion_ambiente_texto_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'presion_ambiente_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'p [bar]');

		handles.humedad_relativa_ambiente_texto_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'humedad_relativa_ambiente_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Humedad';'relativa [%]'});
        
        handles.tipo_combustible_texto_caldera = uicontrol( ...
			'Parent', handles.panel_combustible_caldera, ...
			'Tag', 'tipo_combustible_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 9.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');
        
        handles.empresa_combustible_texto_caldera = uicontrol( ...
			'Parent', handles.panel_combustible_caldera, ...
			'Tag', 'empresa_combustible_texto_caldera', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 5.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Empresa');
   
        % TURBINA GAS STATIC TEXTS-----------------------------
        
         handles.tipo_texto_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'tipo_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');

		handles.presion_alta_texto_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'presion_alta_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 6 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'p alta';'[bar]'});

		handles.presion_baja_texto_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'presion_baja_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'p baja';'[bar]'});
        
        handles.caudal_texto_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'caudal_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.4 9.4692307692308 22.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Caudal aire';'[m3/s]'});

		handles.potencia_texto_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'potencia_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.5 6 17.4 2.8], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Potencia';'[MW]'});
        
		handles.EGR_texto_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'EGR_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.4 2.65384615384615 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'EGR [%]');

		handles.temperatura_ambiente_texto_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'temperatura_ambiente_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 10.8461538461538 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'T [ºC]');

		handles.presion_ambiente_texto_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'presion_ambiente_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 7 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'p [bar]');

		handles.humedad_relativa_ambiente_texto_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'humedad_relativa_ambiente_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [7 2.23076923076923 17.4 3.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Humedad';'relativa [%]'});
        
        handles.tipo_combustible_texto_turbina = uicontrol( ...
			'Parent', handles.panel_combustible_turbina, ...
			'Tag', 'tipo_combustible_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 9.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Tipo');
        
        handles.empresa_combustible_texto_turbina = uicontrol( ...
			'Parent', handles.panel_combustible_turbina, ...
			'Tag', 'empresa_combustible_texto_turbina', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.6 5.2 17.4 1.3], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', 'Empresa');
        
        
        % OTRO ESTUDIO STATIC TEXTS-----------------------------------
        
        handles.texto_otro = uicontrol( ...
			'Parent', handles.panel_otro, ...
			'Tag', 'texto_otro', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [5.5 6 17.4 2.8], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'Nuevo';'estudio'});
        
		% --- PUSHBUTTONS -------------------------------------
        
        handles.atras_boton = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'atras_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [148.8 3.3 22.4 2.38461538461538], ...
			'String', '< Atrás', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @atras_boton_Callback);
		
		handles.siguiente_boton = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'siguiente_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [173.2 3.3 22.4 2.38461538461538], ...
			'String', 'Siguiente >', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @siguiente_boton_Callback);

		handles.salir_boton = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'salir_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [197.6 3.3 22.4 2.38461538461538], ...
			'String', 'Salir', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @salir_boton_Callback);
        
        % --- RADIO BUTTONS -------------------------------------
        
        handles.MCIA_boton = uicontrol( ...
            'Parent', handles.aplicacion_panel, ...
            'Tag', 'MCIA_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 14.8 25.4 1.76923076923077], ...
            'String', 'MCIA', ...
            'value', 1, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @MCIA_boton_Callback);
        
         handles.quemador_boton = uicontrol( ...
            'Parent', handles.aplicacion_panel, ...
            'Tag', 'quemador_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 11.6 25.4 1.76923076923077], ...
            'String', 'Quemador', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @quemador_boton_Callback);
        
        handles.caldera_boton = uicontrol( ...
            'Parent', handles.aplicacion_panel, ...
            'Tag', 'caldera_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 8.4 25.4 1.76923076923077], ...
            'String', 'Caldera', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @caldera_boton_Callback);
        
        handles.turbina_boton = uicontrol( ...
            'Parent', handles.aplicacion_panel, ...
            'Tag', 'turbina_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 5.2 25.4 1.76923076923077], ...
            'String', 'Turbina de gas', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @turbina_boton_Callback);
        
        handles.otro_boton = uicontrol( ...
            'Parent', handles.aplicacion_panel, ...
            'Tag', 'otro_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 2 25.4 1.76923076923077], ...
            'String', 'Otro estudio', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @otro_boton_Callback);
        
		% --- EDIT TEXTS -------------------------------------
        
        % MCIA EDIT TEXTS---------------------------------
		handles.tipo_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'tipo_mot', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 11.2 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.S_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'S', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 8.1 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'S [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.D_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'D', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 5.1 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'D [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.p_mot_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_motor_MCIA, ...
			'Tag', 'p_mot', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 2.15 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.n_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'n', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.1153846153846 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'n [rpm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.M_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'M', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.05 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'M [Nm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.egr_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_funcionamiento_MCIA, ...
			'Tag', 'egr', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 2.3 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'EGR [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.T_amb_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'T_amb', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'T [ºC]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.p_amb_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'p_amb', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.w_r_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_ambiente_MCIA, ...
			'Tag', 'w_r', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'w r [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.tipo_combustible_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_combustible_MCIA, ...
			'Tag', 'tipo_combustible_entrada', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 9 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.empresa_combustible_entrada_MCIA = uicontrol( ...
			'Parent', handles.panel_combustible_MCIA, ...
			'Tag', 'empresa_combustible_entrada', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Empresa', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        % QUEMADOR EDIT TEXTS--------------------------------
        
        handles.tipo_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'tipo_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.altura_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'altura_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'h [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.diametro_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_quemador, ...
			'Tag', 'diametro_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'D [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.oxidante_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'oxidante_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Oxidante', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.dosado_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'dosado_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Dosado', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.caudal_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_funcionamiento_quemador, ...
			'Tag', 'caudal_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Q [m3/s]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.T_amb_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'T_amb_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'T [ºC]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.p_amb_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'p_amb_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.w_r_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_ambiente_quemador, ...
			'Tag', 'w_r_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'w r [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.tipo_combustible_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_combustible_quemador, ...
			'Tag', 'tipo_combustible_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 9 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.empresa_combustible_entrada_quemador = uicontrol( ...
			'Parent', handles.panel_combustible_quemador, ...
			'Tag', 'empresa_combustible_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Empresa', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        % CALDERA EDIT TEXTS---------------------------------
        
        handles.tipo_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'tipo_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.altura_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'altura_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'h [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.diametro_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_caldera, ...
			'Tag', 'diametro_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'D [mm]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.dosado_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'dosado_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Dosado', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.egr_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'EGR_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'EGR [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.caudal_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_funcionamiento_caldera, ...
			'Tag', 'caudal_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Q [m3/s]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.T_amb_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'T_amb_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'T [ºC]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.p_amb_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'p_amb_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.w_r_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_ambiente_caldera, ...
			'Tag', 'w_r_entrada_quemador', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'w r [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.tipo_combustible_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_combustible_caldera, ...
			'Tag', 'tipo_combustible_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 9 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.empresa_combustible_entrada_caldera = uicontrol( ...
			'Parent', handles.panel_combustible_caldera, ...
			'Tag', 'empresa_combustible_entrada_caldera', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Empresa', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        % TURBINA GAS EDIT TEXTS-----------------------------
        
         handles.tipo_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'tipo_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.presion_alta_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'presion_alta_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.presion_baja_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_turbina, ...
			'Tag', 'presion_baja_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.caudal_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'caudal_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.1153846153846 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Q [m3/s]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.potencia_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'potencia_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.05 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'P [MW]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.egr_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_funcionamiento_turbina, ...
			'Tag', 'egr_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 2.3 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'EGR [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.T_amb_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'T_amb_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 10.5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'T [ºC]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.p_amb_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'p_amb_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.65 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p [bar]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');

		handles.w_r_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_ambiente_turbina, ...
			'Tag', 'w_r_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 3.07692307692308 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'w r [%]', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.tipo_combustible_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_combustible_turbina, ...
			'Tag', 'tipo_combustible_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 9 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Tipo', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        handles.empresa_combustible_entrada_turbina = uicontrol( ...
			'Parent', handles.panel_combustible_turbina, ...
			'Tag', 'empresa_combustible_entrada_turbina', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 5 20 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Empresa', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        % OTRO ESTUDIO EDIT TEXTS---------------------------------
        
        handles.entrada_otro = uicontrol( ...
			'Parent', handles.panel_otro, ...
			'Tag', 'entrada_otro', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [30 6.05 89 1.9], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Introduzca el nombre de la aplicación', ...
            'FontSize', 12, ...
            'FontName', 'Candara');
        
        
        movegui(handles.figure1,'center')

    end

%% ---------------------------------------------------------------------------
    function MCIA_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.quemador_boton,'value')==1
            set(handles.quemador_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','on');
            set(handles.panel_funcionamiento_MCIA,'visible','on');
            set(handles.panel_ambiente_MCIA,'visible','on');
            set(handles.panel_combustible_MCIA,'visible','on');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.caldera_boton,'value')==1
            set(handles.caldera_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','on');
            set(handles.panel_funcionamiento_MCIA,'visible','on');
            set(handles.panel_ambiente_MCIA,'visible','on');
            set(handles.panel_combustible_MCIA,'visible','on');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.turbina_boton,'value')==1
            set(handles.turbina_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','on');
            set(handles.panel_funcionamiento_MCIA,'visible','on');
            set(handles.panel_ambiente_MCIA,'visible','on');
            set(handles.panel_combustible_MCIA,'visible','on');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.otro_boton,'value')==1
            set(handles.otro_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','on');
            set(handles.panel_funcionamiento_MCIA,'visible','on');
            set(handles.panel_ambiente_MCIA,'visible','on');
            set(handles.panel_combustible_MCIA,'visible','on');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.MCIA_boton,'value')==0
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        else            
            set(handles.panel_motor_MCIA,'visible','on');
            set(handles.panel_funcionamiento_MCIA,'visible','on');
            set(handles.panel_ambiente_MCIA,'visible','on');
            set(handles.panel_combustible_MCIA,'visible','on');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
        end
        
        setappdata(0,'Aplicacion','MCIA');
    end
    

%% ---------------------------------------------------------------------------
   function quemador_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.MCIA_boton,'value')==1
            set(handles.MCIA_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','on');
            set(handles.panel_funcionamiento_quemador,'visible','on');
            set(handles.panel_ambiente_quemador,'visible','on');
            set(handles.panel_combustible_quemador,'visible','on');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.caldera_boton,'value')==1
            set(handles.caldera_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','on');
            set(handles.panel_funcionamiento_quemador,'visible','on');
            set(handles.panel_ambiente_quemador,'visible','on');
            set(handles.panel_combustible_quemador,'visible','on');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.turbina_boton,'value')==1
            set(handles.turbina_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','on');
            set(handles.panel_funcionamiento_quemador,'visible','on');
            set(handles.panel_ambiente_quemador,'visible','on');
            set(handles.panel_combustible_quemador,'visible','on');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.otro_boton,'value')==1
            set(handles.otro_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','on');
            set(handles.panel_funcionamiento_quemador,'visible','on');
            set(handles.panel_ambiente_quemador,'visible','on');
            set(handles.panel_combustible_quemador,'visible','on');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');    
            
        elseif get(handles.quemador_boton,'value')==0
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');   
            
        else            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','on');
            set(handles.panel_funcionamiento_quemador,'visible','on');
            set(handles.panel_ambiente_quemador,'visible','on');
            set(handles.panel_combustible_quemador,'visible','on');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');   
        end
        
        setappdata(0,'Aplicacion','Quemador');
   end


%% ---------------------------------------------------------------------------
   function caldera_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.MCIA_boton,'value')==1
            set(handles.MCIA_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','on');
            set(handles.panel_funcionamiento_caldera,'visible','on');
            set(handles.panel_ambiente_caldera,'visible','on');
            set(handles.panel_combustible_caldera,'visible','on');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');   
            
        elseif get(handles.quemador_boton,'value')==1
            set(handles.quemador_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','on');
            set(handles.panel_funcionamiento_caldera,'visible','on');
            set(handles.panel_ambiente_caldera,'visible','on');
            set(handles.panel_combustible_caldera,'visible','on');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');   
            
        elseif get(handles.turbina_boton,'value')==1
            set(handles.turbina_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','on');
            set(handles.panel_funcionamiento_caldera,'visible','on');
            set(handles.panel_ambiente_caldera,'visible','on');
            set(handles.panel_combustible_caldera,'visible','on');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');  
            
        elseif get(handles.otro_boton,'value')==1
            set(handles.otro_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','on');
            set(handles.panel_funcionamiento_caldera,'visible','on');
            set(handles.panel_ambiente_caldera,'visible','on');
            set(handles.panel_combustible_caldera,'visible','on');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');    
            
        elseif get(handles.caldera_boton,'value')==0
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        else            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','on');
            set(handles.panel_funcionamiento_caldera,'visible','on');
            set(handles.panel_ambiente_caldera,'visible','on');
            set(handles.panel_combustible_caldera,'visible','on');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
        end
        
        setappdata(0,'Aplicacion','Caldera');
   end


%% ---------------------------------------------------------------------------
   function turbina_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.MCIA_boton,'value')==1
            set(handles.MCIA_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','on');
            set(handles.panel_funcionamiento_turbina,'visible','on');
            set(handles.panel_ambiente_turbina,'visible','on');
            set(handles.panel_combustible_turbina,'visible','on');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.quemador_boton,'value')==1
            set(handles.quemador_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','on');
            set(handles.panel_funcionamiento_turbina,'visible','on');
            set(handles.panel_ambiente_turbina,'visible','on');
            set(handles.panel_combustible_turbina,'visible','on');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.caldera_boton,'value')==1
            set(handles.caldera_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','on');
            set(handles.panel_funcionamiento_turbina,'visible','on');
            set(handles.panel_ambiente_turbina,'visible','on');
            set(handles.panel_combustible_turbina,'visible','on');
            
            set(handles.panel_otro,'visible','off');
            
        elseif get(handles.otro_boton,'value')==1
            set(handles.otro_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','on');
            set(handles.panel_funcionamiento_turbina,'visible','on');
            set(handles.panel_ambiente_turbina,'visible','on');
            set(handles.panel_combustible_turbina,'visible','on');
            
            set(handles.panel_otro,'visible','off');    
            
        elseif get(handles.turbina_boton,'value')==0
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        else            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','on');
            set(handles.panel_funcionamiento_turbina,'visible','on');
            set(handles.panel_ambiente_turbina,'visible','on');
            set(handles.panel_combustible_turbina,'visible','on');
            
            set(handles.panel_otro,'visible','off');
        end
        
        setappdata(0,'Aplicacion','Turbina');
   end

%% ---------------------------------------------------------------------------
   function otro_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.MCIA_boton,'value')==1
            set(handles.MCIA_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','on');
            
        elseif get(handles.quemador_boton,'value')==1
            set(handles.quemador_boton,'value',0);
            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','on');
            
        elseif get(handles.caldera_boton,'value')==1
            set(handles.caldera_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','on');
            
        elseif get(handles.turbina_boton,'value')==1
            set(handles.turbina_boton,'value',0);
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','on');    
            
        elseif get(handles.otro_boton,'value')==0
           
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','off');
            
        else            
            set(handles.panel_motor_MCIA,'visible','off');
            set(handles.panel_funcionamiento_MCIA,'visible','off');
            set(handles.panel_ambiente_MCIA,'visible','off');
            set(handles.panel_combustible_MCIA,'visible','off');
            
            set(handles.panel_quemador,'visible','off');
            set(handles.panel_funcionamiento_quemador,'visible','off');
            set(handles.panel_ambiente_quemador,'visible','off');
            set(handles.panel_combustible_quemador,'visible','off');
            
            set(handles.panel_caldera,'visible','off');
            set(handles.panel_funcionamiento_caldera,'visible','off');
            set(handles.panel_ambiente_caldera,'visible','off');
            set(handles.panel_combustible_caldera,'visible','off');
            
            set(handles.panel_turbina,'visible','off');
            set(handles.panel_funcionamiento_turbina,'visible','off');
            set(handles.panel_ambiente_turbina,'visible','off');
            set(handles.panel_combustible_turbina,'visible','off');
            
            set(handles.panel_otro,'visible','on');
        end
        
        setappdata(0,'Aplicacion','Otro');
    end
%% ---------------------------------------------------------------------------
	function atras_boton_Callback(hObject,evendata) %#ok<INUSD>
        close;
        Tipo_fractal_build;
	end
%% ---------------------------------------------------------------------------
	function siguiente_boton_Callback(hObject,evendata) %#ok<INUSD>
       
        handles.aplicacion=getappdata(0,'Aplicacion');
        
        if strcmp(handles.aplicacion,'MCIA')
        setappdata(0,'tipo_mot',get(handles.tipo_entrada_MCIA,'string'));
        setappdata(0,'S',get(handles.S_entrada_MCIA,'string'));
        setappdata(0,'D',get(handles.D_entrada_MCIA,'string'));
        setappdata(0,'p_mot',get(handles.p_mot_entrada_MCIA,'string'));
        setappdata(0,'n',get(handles.n_entrada_MCIA,'string'));
        setappdata(0,'M',get(handles.M_entrada_MCIA,'string'));
        setappdata(0,'egr',get(handles.egr_entrada_MCIA,'string'));
        setappdata(0,'T_amb',get(handles.T_amb_entrada_MCIA,'string'));
        setappdata(0,'p_amb',get(handles.p_amb_entrada_MCIA,'string'));
        setappdata(0,'w_r',get(handles.w_r_entrada_MCIA,'string'));
        setappdata(0,'tipo_comb',get(handles.tipo_combustible_entrada_MCIA,'string'));
        setappdata(0,'empresa_comb',get(handles.empresa_combustible_entrada_MCIA,'string'));
        end
        
        if strcmp(handles.aplicacion,'Quemador')
        setappdata(0,'tipo_quemador',get(handles.tipo_entrada_quemador,'string'));
        setappdata(0,'altura',get(handles.altura_entrada_quemador,'string'));
        setappdata(0,'diametro',get(handles.diametro_entrada_quemador,'string'));
        setappdata(0,'oxidante',get(handles.oxidante_entrada_quemador,'string'));
        setappdata(0,'dosado',get(handles.dosado_entrada_quemador,'string'));
        setappdata(0,'caudal',get(handles.caudal_entrada_quemador,'string'));
        setappdata(0,'T_amb',get(handles.T_amb_entrada_quemador,'string'));
        setappdata(0,'p_amb',get(handles.p_amb_entrada_quemador,'string'));
        setappdata(0,'w_r',get(handles.w_r_entrada_quemador,'string'));
        setappdata(0,'tipo_comb',get(handles.tipo_combustible_entrada_quemador,'string'));
        setappdata(0,'empresa_comb',get(handles.empresa_combustible_entrada_quemador,'string'));
        end
        
        if strcmp(handles.aplicacion,'Caldera')
        setappdata(0,'tipo_caldera',get(handles.tipo_entrada_caldera,'string'));
        setappdata(0,'altura',get(handles.altura_entrada_caldera,'string'));
        setappdata(0,'diametro',get(handles.diametro_entrada_caldera,'string'));
        setappdata(0,'dosado',get(handles.dosado_entrada_caldera,'string'));
        setappdata(0,'egr',get(handles.egr_entrada_caldera,'string'));
        setappdata(0,'caudal',get(handles.caudal_entrada_caldera,'string'));
        setappdata(0,'T_amb',get(handles.T_amb_entrada_caldera,'string'));
        setappdata(0,'p_amb',get(handles.p_amb_entrada_caldera,'string'));
        setappdata(0,'w_r',get(handles.w_r_entrada_caldera,'string'));
        setappdata(0,'tipo_comb',get(handles.tipo_combustible_entrada_caldera,'string'));
        setappdata(0,'empresa_comb',get(handles.empresa_combustible_entrada_caldera,'string'));
        end
        
        if strcmp(handles.aplicacion,'Turbina')
        setappdata(0,'tipo_turbina',get(handles.tipo_entrada_turbina,'string'));
        setappdata(0,'p_alta',get(handles.presion_alta_entrada_turbina,'string'));
        setappdata(0,'p_baja',get(handles.presion_baja_entrada_turbina,'string'));
        setappdata(0,'caudal',get(handles.caudal_entrada_turbina,'string'));
        setappdata(0,'potencia',get(handles.potencia_entrada_turbina,'string'));
        setappdata(0,'egr',get(handles.egr_entrada_turbina,'string'));
        setappdata(0,'T_amb',get(handles.T_amb_entrada_turbina,'string'));
        setappdata(0,'p_amb',get(handles.p_amb_entrada_turbina,'string'));
        setappdata(0,'w_r',get(handles.w_r_entrada_turbina,'string'));
        setappdata(0,'tipo_comb',get(handles.tipo_combustible_entrada_turbina,'string'));
        setappdata(0,'empresa_comb',get(handles.empresa_combustible_entrada_turbina,'string'));
        end
        
        if strcmp(handles.aplicacion,'Otro')
        setappdata(0,'otro_estudio',get(handles.entrada_otro,'string'));
        end
        
        close;
        if strcmp(handles.granulado,'Si')
        Datos_imagenes_build;
        elseif strcmp(handles.granulado,'Si_voxel')
        Datos_imagenes_granuladovoxel_build;
        else
        Datos_imagenes_nogranulado_build;
        end
    end

%% ---------------------------------------------------------------------------
	function salir_boton_Callback(hObject,evendata) %#ok<INUSD>
        app=getappdata(0); %get all the appdata of 0
        %and then
        appdatas = fieldnames(app);
        for kA = 1:length(appdatas)
            rmappdata(0,appdatas{kA});
        end
        close all;
	end

end
