function fig_hdl = information_build
% INFORMACION_BUILD
%-------------------------------------------------------------------------------
% File name   : information_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 32], ...
			'Name', 'Information', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 4 140.2 25], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'In this new FRAKTAL version the user can check, if wished, the underestimation of the gyration radius of the agglomerates, and consequently can also check the underestimation of the fractal dimension of them, owing to the 2D projection of the three-dimensional structures:',' ','     1. Choose the box ''Yes'' in case you wish to check the gyration radius from 2D into 3D applying the correction Rg 3D= Rg 2D+A*Rg 2D^B; where A=(2.165-19.315*(delta-1))*10^-5 and B=2.928+5.414*(delta-1), and also using a new shape parameter m=1.86-1.3*(delta-1), delta being the sintering coefficient.','','     2. Choose the box ''No'' if, on the contrary, you do not wish to check the gyration radius and make the calculations with 2D gyration radius and with a shape parameter m = 1.95.','',''}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end