function fig_hdl = informacion_build
% INFORMACION_BUILD
%-------------------------------------------------------------------------------
% File name   : informacion_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 32], ...
			'Name', 'Información', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 4 140.2 25], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'En esta nueva versión de FRAKTAL el usuario puede corregir, si lo desea, la subestimación del radio de giro de los aglomerados, y por consiguiente también corregir la sobreestimación de la dimensión fractal de los mismos, ambas debidas a la proyección en 2D de las estructuras tridimensionales:',' ','     1. Elegir la casilla "Sí" en el caso de que se desee corregir el radio de giro en 2D a 3D aplicando la corrección Rg 3D= Rg 2D+A*Rg 2D^B; donde A=(2.165-19.315*(delta-1))*10^-5 y B=2.928+5.414*(delta-1), y además utilizar un nuevo factor de forma m=1.86-1.3*(delta-1), siendo delta el coeficiente de aplastamiento.','','     2. Elegir la casilla "No" si por el contrario no se desea corregir el radio de giro y realizar los cálculos con el radio de giro en 2D y con un factor de forma m= 1.95.','',''}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end