function fig_hdl = instructions_build
% INSTRUCCIONES_BUILD
%-------------------------------------------------------------------------------
% File name   : instructions_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 55], ...
			'Name', 'instructions', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- AXES -------------------------------------
		handles.img_instrucciones_axes = axes( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'axes1', ...
			'Units', 'characters', ...
			'Position', [9.8 3.84615384615385 140.2 21.9230769230769]);
        
            axes(handles.img_instrucciones_axes)
            background = imread('explicacion.jpg');
            axis off;
            imshow(background);

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 26 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'1. Select with the first button the folder where all the images are located. Images named in the Excel file but not located in the folder will not be considered.',' ','2. Data file must be an Excel file. These are the steps to create the file:','','     i. First column: Number of the image to be analized. Only numbers are allowed.','     ii. Second column: Number of pixels per 100nm of the image [Pix/100nm].','     iii. Third and last column: Average particle diameters in nm. It is derived from the average of 10 selected particles from that image [dpo(nm)].','     iv. At the beginning of each row with comments, titles or not desired numeric information must show the symbol %.',' ','3. Press button "Take data" to select the .xls file or .xlsx file created in step 2.'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end

%'1. Select with the first button the folder where all the images are located. Images named in the Excel file but not located in the folder will not be considered.',' ','2. The data file must be an Excel file. These are the steps to create the file:','','     i. In the first column must be the number of the image to analize. Only numbers are allowed.','     ii.In the second column are located the number of pixels per 100nm of the image [Pix/100nm].','     iii. In the third and last column are located the average bore of the particles in nm. It is derived from the average of the length of 10 random particles of that image [dpo(nm)].',''     iv. Rows with no data or with data that do not want to see (e.g. row with headers or some rows with comments), must have the symbol at the beginning of the row.',' ','3. Press the button "Take data" to select the .xls file or .xlsx file created in the step 2.'
