function fig_hdl = instructions_grupo_build
% INSTRUCCIONES_GRUPO_BUILD
%-------------------------------------------------------------------------------
% File name   : instructions_grupo_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 20], ...
			'Name', 'Instructions', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 -5 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Select in this screen the group upload mode that you wish to study:',' ','     1. Choose the option ''No Excel file upload''. This option is the right one if all the images that are to be analyzed share the same number of pixels for every 100 nm [Pix/100nm] and the same average particles diameter [dpo(nm)]. This option allows to introduce those data manually. No need to upload an Excel file. ','','     2. Choose the option ''Excel file upload''. This option is the right one if the images that are to be studied do not have the same number of pixels for every 100nm [Pix/100nm], or they do not have the same average particles diameter [dpo(nm)]. In that case, these data must be introduce with an Excel file.'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end