function fig_hdl = instructions_nuevo_build
% INSTRUCCIONES_NUEVO_BUILD
%-------------------------------------------------------------------------------
% File name   : instructions_nuevo_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 20], ...
			'Name', 'Instructions', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));
                  
		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 -5 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'1. Select with the first button the folder where all the images are located. Images named in the Excel file but not located in the folder will not be considered.',' ','2. In the box "nºpixels/100nm" write the number of pixels in common with all the images for every 100 nm [Pix/100nm].','','3. In he box "Average particles diameter" write the common average particles diameter in nm, obtained from the aritmetic average of 10 particles with certain features of each image [dp0(nm)].'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end