function fig_hdl = instrucciones_build
% INSTRUCCIONES_BUILD
%-------------------------------------------------------------------------------
% File name   : instrucciones_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 55], ...
			'Name', 'Instrucciones', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- AXES -------------------------------------
		handles.img_instrucciones_axes = axes( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'axes1', ...
			'Units', 'characters', ...
			'Position', [9.8 3.84615384615385 140.2 21.9230769230769]);
        
            axes(handles.img_instrucciones_axes)
            background = imread('explicacion.jpg');
            axis off;
            imshow(background);

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 26 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'1. Seleccionar con el primer botón la carpeta donde está situado el grupo de imágenes que se quiere examinar. Si alguna imagen citada no está en la carpeta no se tendrá en cuenta.',' ','2. El archivo de datos debe ser un archivo Excel. Se deben tener en cuenta las siguientes indicaciones:',' ','     i. En la primera columna debe aparecer el número de la imagen a analizar. Sólo se permiten números.','     ii. En la segunda columna se sitúa el nº de pixeles de la imagen por cada 100nm [Pix/100nm].','     iii. En la tercera y última columna se escribe el diámetro de partículas medio en nm, obtenido a partir de la media de 10 partículas con ciertas características de esa imagen [dp0(nm)].','     iv. Al principio de las filas que contienen comentarios, títulos o información numérica que no se desea tener en cuenta debe añadirse el símbolo %.',' ','3. Pulsar el botón "subir archivo de datos" para seleccionar el archivo .xls o .xlsx creado en el apartado anterior.'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end
