function fig_hdl = instrucciones_grupo_build
% INSTRUCCIONES_GRUPO_BUILD
%-------------------------------------------------------------------------------
% File name   : instrucciones_grupo_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 20], ...
			'Name', 'Instrucciones', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 -5 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Seleccionar en esta pantalla el modo de subida del grupo de imágenes que se desea estudiar:',' ','     1. Elegir la opción "Subida sin archivo Excel". Esta opción es la adecuada si todas las imágenes que se van a analizar comparten el mismo nº de píxeles por cada 100nm [Pix/100nm] y el mismo diámetro de partículas medio [dp0(nm)]. Esta opción permite introducir dichos datos manualmente sin necesidad de subir un archivo Excel. ','','     2. Elegir la opción "Subida con archivo Excel". Esta opción es la adecuada si las imágenes que se desean estudiar no tienen el mismo nº de píxeles por cada 100nm [Pix/100nm], o bien no tienen el mismo diámetro de partículas medio [dp0(nm)], en cuyo caso se deberán proporcionar estos datos mediante un archivo Excel.'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end