function fig_hdl = instrucciones_nuevo_build
% INSTRUCCIONES_NUEVO_BUILD
%-------------------------------------------------------------------------------
% File name   : instrucciones_nuevo_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figura_instrucciones;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figura_instrucciones = figure( ...
			'Tag', 'figura_instrucciones', ...
			'Units', 'characters', ...
			'Position', [102.8 5.07692307692308 162.2 20], ...
			'Name', 'Instrucciones', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));
                  
		% --- STATIC TEXTS -------------------------------------
		handles.instrucciones_texto = uicontrol( ...
			'Parent', handles.figura_instrucciones, ...
			'Tag', 'instrucciones_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [9.8 -5 140.2 23], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'1. Seleccionar con el primer botón la carpeta donde está situado el grupo de imágenes que se quiere examinar. Si alguna imagen citada no está en la carpeta no se tendrá en cuenta.',' ','2. En la casilla "nºpixeles/100nm" escribir el número de píxeles común de todas las imágenes por cada 100nm [Pix/100nm].','','3. En la casilla "Diámetro medio de las partículas" escribir el diámetro medio común de las partículas en nm, obtenido a partir de la media de 10 partículas con ciertas características de cada imagen [dp0(nm)].'}, ...
			'HorizontalAlignment', 'left');

        movegui(handles.figura_instrucciones,'center')
	end

end