function fig_hdl = Tipo_fractal_build
% TIPO_FRACTAL_BUILD
%-------------------------------------------------------------------------------
% File name   : Tipo_fractal_build.m
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figuraimagenes;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figuraimagenes = figure( ...
			'Tag', 'figuraimagenes', ...
			'Units', 'characters', ...
			'Position', [25.4 0.923076923076923 260 53.8461538461538], ...
			'Name', 'Tipo_fractal', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off',...
			'Color', [0.4 0.6 1]);

		% --- PANELS -------------------------------------
        handles.panel_fractal_granulado = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'panel_fractal_granulado', ...
			'Units', 'characters', ...
			'Position', [44 46 80 3], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'on', ...
            'Title', '');
        
        handles.panel_fractal_no_granulado = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'panel_fractal_no_granulado', ...
			'Units', 'characters', ...
			'Position', [165 46 80 3], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'on', ...
            'Title', '');
        
        handles.calculo_fractal_esfera = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'calculo_fractal_esfera', ...
			'Units', 'characters', ...
			'Position', [2 35.5 80 10], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');
        
        handles.calculo_fractal_voxel = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'calculo_fractal_voxel', ...
			'Units', 'characters', ...
			'Position', [83.499 35.5 80 10], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');
        
		handles.fractal_no_granulado = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'fractal_granulado', ...
			'Units', 'characters', ...
			'Position', [2 5 80 30], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');
        
        handles.fractal_no_granulado_voxel = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'fractal_granulado_voxel', ...
			'Units', 'characters', ...
			'Position', [83.499 5 80 30], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');
        
        handles.calculo_nofractal_voxel = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'calculo_nofractal_voxel', ...
			'Units', 'characters', ...
			'Position', [165 35.5 80 10], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');

		handles.fractal_granulado = uipanel( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'fractal_no_granulado', ...
			'Units', 'characters', ...
			'Position', [165 5 80 30], ...
            'HighlightColor', [1 0.35 0], ...
            'visible', 'off', ...
            'Title', '');

		% --- STATIC TEXTS -------------------------------------

        handles.titulo_imagenes_texto = uicontrol( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'titulo_imagenes_texto', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [115 49.5 30.2 3.2], ...
			'String', 'TIPO DE FRACTAL RAMIFICADO', ...
            'FontSize', 15, ...
            'FontName', 'Candara', ...
            'Backgroundcolor', [0.4 0.6 1],...
            'Foregroundcolor', [1 1 1]);
        
		handles.npix_texto = uicontrol( ...
			'Parent', handles.fractal_no_granulado, ...
			'Tag', 'npix_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 24.5 75 4.5], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Esta opción solo es válida para estructuras fractales ramificadas que están formadas por partículas cuyas formas se asemejan a esferas.'}, ...
			'HorizontalAlignment', 'left');
        
        handles.granulado_voxel_texto = uicontrol( ...
			'Parent', handles.fractal_no_granulado_voxel, ...
			'Tag', 'granulado_voxel_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 24.5 75 4.5], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Esta opción permite estudiar mediante vóxeles estructuras fractales ramificadas que están formadas por partículas cuyas formas se asemejan a esferas.'}, ...
			'HorizontalAlignment', 'left');

		handles.dir_img_texto = uicontrol( ...
			'Parent', handles.fractal_granulado, ...
			'Tag', 'dir_img_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 25 75 4], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'La voxelización permite el estudio de cualquier tipo de imagen con geometría fractal ramificada.'}, ...
			'HorizontalAlignment', 'left');
        
         handles.calculo_fractal_esfera_texto = uicontrol( ...
			'Parent', handles.calculo_fractal_esfera, ...
			'Tag', 'calculo_fractal_esfera_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 1 75 5], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Seleccionar esta opción si se desea realizar el análisis fractal de las imágenes utilizando partículas primarias esféricas como elementos básicos de cálculo.'}, ...
			'HorizontalAlignment', 'left');
        
        handles.calculo_fractal_voxel_texto = uicontrol( ...
			'Parent', handles.calculo_fractal_voxel, ...
			'Tag', 'calculo_fractal_voxel_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 0 75 6], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Seleccionar esta opción, si a pesar de estudiar fractales formados por partículas esféricas, se desea realizar el análisis fractal de las imágenes utilizando vóxeles como elementos básicos de cálculo.'}, ...
			'HorizontalAlignment', 'left');
        
        handles.calculo_voxel_texto = uicontrol( ...
			'Parent', handles.calculo_nofractal_voxel, ...
			'Tag', 'calculo_voxel_texto', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [1 1 75 5], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
			'String', {'Al seleccionar esta opción se realiza el análisis fractal de las imágenes utilizando vóxeles como elementos básicos de cálculo.'}, ...
			'HorizontalAlignment', 'left');
        
        handles.calculo_voxel = uicontrol( ...
			'Parent', handles.calculo_nofractal_voxel, ...
			'Tag', 'calculo_voxel', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [18 6.3 50 1.76923076923077], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
			'String', {'CÁLCULO BASADO EN VÓXELES'}, ...
			'HorizontalAlignment', 'left');

		% --- PUSHBUTTONS -------------------------------------
        
        handles.atras_boton = uicontrol( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'atras_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [173.8 2.15384615384615 22.4 2.38461538461538], ...
			'String', '< Atrás', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @atras_boton_Callback);
        
		handles.siguiente_boton = uicontrol( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'siguiente_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [198.2 2.15384615384615 22.4 2.38461538461538], ...
			'String', 'Siguiente >', ...
            'enable', 'off', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @siguiente_boton_Callback);

		handles.salir_boton = uicontrol( ...
			'Parent', handles.figuraimagenes, ...
			'Tag', 'salir_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [222.6 2.15384615384615 22.4 2.38461538461538], ...
			'String', 'Salir', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
			'Callback', @salir_boton_Callback);

		% --- RADIO BUTTONS -------------------------------------
		handles.frac_no_granulado = uicontrol( ...
			'Parent', handles.panel_fractal_granulado, ...
			'Tag', 'frac_no_granulado', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [12 0.4 60 1.76923076923077], ...
			'String', 'FRACTAL RAMIFICADO GRANULADO', ...
            'value', 0, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...            
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @frac_no_granulado_Callback);
        
        handles.frac_no_granulado_esfera = uicontrol( ...
			'Parent', handles.calculo_fractal_esfera, ...
			'Tag', 'frac_no_granulado_esfera', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [6 6.5 70 1.76923076923077], ...
			'String', 'CÁLCULO BASADO EN PRIMARIAS ESFÉRICAS', ...
            'value', 0, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...            
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @frac_no_granulado_esfera_Callback);
        
        handles.frac_no_granulado_voxel = uicontrol( ...
			'Parent', handles.calculo_fractal_voxel, ...
			'Tag', 'frac_no_granulado_voxel', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [16 6.5 50 1.76923076923077], ...
			'String', 'CÁLCULO BASADO EN VÓXELES', ...
            'value', 0, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...            
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @frac_no_granulado_voxel_Callback);

		handles.frac_granulado = uicontrol( ...
			'Parent', handles.panel_fractal_no_granulado, ...
			'Tag', 'frac_granulado', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [10 0.4 60 1.76923076923077], ...
			'String', 'FRACTAL RAMIFICADO NO GRANULADO', ...
            'value', 0, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @frac_granulado_Callback);
        
        % --- IMAGES -------------------------------------------
         handles.uclm_axes = axes( ...
			'Parent', handles.fractal_granulado, ...
			'Tag', 'uclm_axes', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [1 -12 50 50]);
        
            set(handles.uclm_axes,'visible','on');
            axes(handles.uclm_axes)
            background = imread('Rayooo.png');
            axis off;
            imshow(background);
            
            handles.voxel_axes = axes( ...
			'Parent', handles.fractal_granulado, ...
			'Tag', 'voxel_axes', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [40 0.2 37 37]);
        
            set(handles.voxel_axes,'visible','on');
            axes(handles.voxel_axes)
            background = imread('voxel.png');
            axis off;
            imshow(background);
            
            handles.aglo_voxel = axes( ...
			'Parent', handles.fractal_no_granulado_voxel, ...
			'Tag', 'aglo_voxel', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [21 -6 60 40]);
        
            set(handles.aglo_voxel,'visible','on');
            axes(handles.aglo_voxel)
            background = imread('Aglo.png');
            axis off;
            imshow(background);
            
            handles.voxel_granulado_axes = axes( ...
			'Parent', handles.fractal_no_granulado_voxel, ...
			'Tag', 'voxel_granulado_axes', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [1 -12.5 37 37]);
        
            set(handles.voxel_granulado_axes,'visible','on');
            axes(handles.voxel_granulado_axes)
            background = imread('voxel.png');
            axis off;
            imshow(background);
            
            handles.motores_axes = axes( ...
			'Parent', handles.fractal_no_granulado, ...
			'Tag', 'motores_axes', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [7 -20 65 65]);
        
            set(handles.motores_axes,'visible','on');
            axes(handles.motores_axes)
            background = imread('Aglomerado.png');
            axis off;
            imshow(background);
            
            handles.esfera_axes = axes( ...
			'Parent', handles.fractal_no_granulado, ...
			'Tag', 'esfera_axes', ...
			'Units', 'characters', ...
            'visible', 'off', ...
			'Position', [12 -8.5 28 30]);
        
            set(handles.esfera_axes,'visible','on');
            axes(handles.esfera_axes)
            background = imread('esfera.png');
            axis off;
            imshow(background);

        movegui(handles.figuraimagenes,'center')

    end
%% ---------------------------------------------------------------------------
	function frac_no_granulado_Callback(hObject,evendata) %#ok<INUSD>
       if get(handles.frac_granulado,'value')==1
            set(handles.frac_granulado,'value',0);
            set(handles.calculo_nofractal_voxel,'visible','off');
            set(handles.fractal_granulado,'visible','off');
            set(handles.calculo_fractal_esfera,'visible','on');
            set(handles.calculo_fractal_voxel,'visible','on');
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.siguiente_boton,'enable','off');
        elseif get(handles.frac_no_granulado,'value')==0
            set(handles.calculo_nofractal_voxel,'visible','off');
            set(handles.fractal_granulado,'visible','off');
            set(handles.calculo_fractal_esfera,'visible','off');
            set(handles.calculo_fractal_voxel,'visible','off');
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.siguiente_boton,'enable','off');
        else            
            set(handles.calculo_nofractal_voxel,'visible','off');
            set(handles.fractal_granulado,'visible','off');
            set(handles.calculo_fractal_esfera,'visible','on');
            set(handles.calculo_fractal_voxel,'visible','on');
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.siguiente_boton,'enable','off');
       end
	end

%% ---------------------------------------------------------------------------
	function frac_granulado_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.frac_no_granulado,'value')==1
            set(handles.frac_no_granulado,'value',0);
            set(handles.calculo_nofractal_voxel,'visible','on');
            set(handles.fractal_granulado,'visible','on');
            set(handles.calculo_fractal_esfera,'visible','off');
            set(handles.calculo_fractal_voxel,'visible','off');
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.siguiente_boton,'enable','on');
            set(handles.fractal_no_granulado_voxel,'visible','off');
        elseif get(handles.frac_granulado,'value')==0
            set(handles.calculo_nofractal_voxel,'visible','off');
            set(handles.fractal_granulado,'visible','off');
            set(handles.calculo_fractal_esfera,'visible','off');
            set(handles.calculo_fractal_voxel,'visible','off');
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.siguiente_boton,'enable','off');
        else            
            set(handles.calculo_nofractal_voxel,'visible','on');
            set(handles.fractal_granulado,'visible','on');
            set(handles.calculo_fractal_esfera,'visible','off');
            set(handles.calculo_fractal_voxel,'visible','off');
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.siguiente_boton,'enable','on');
        end
        setappdata(0,'Granulado','No');
    end
%% ---------------------------------------------------------------------------
    function frac_no_granulado_esfera_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.frac_no_granulado_voxel,'value')==1
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.fractal_no_granulado,'visible','on');
            set(handles.siguiente_boton,'enable','on');
        elseif get(handles.frac_no_granulado_esfera,'value')==0
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.siguiente_boton,'enable','off');
        else        
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.frac_no_granulado_voxel,'value',0);
            set(handles.fractal_no_granulado,'visible','on');
            set(handles.siguiente_boton,'enable','on');
        end
        setappdata(0,'Granulado','Si');
    end
%% ---------------------------------------------------------------------------
    function frac_no_granulado_voxel_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.frac_no_granulado_esfera,'value')==1
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','on');
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.siguiente_boton,'enable','on');
        elseif get(handles.frac_no_granulado_voxel,'value')==0
            set(handles.fractal_no_granulado_voxel,'visible','off');
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.siguiente_boton,'enable','off');
        else        
            set(handles.fractal_no_granulado,'visible','off');
            set(handles.frac_no_granulado_esfera,'value',0);
            set(handles.fractal_no_granulado_voxel,'visible','on');
            set(handles.siguiente_boton,'enable','on');
        end
        setappdata(0,'Granulado','Si_voxel');
    end
%% ---------------------------------------------------------------------------
	function atras_boton_Callback(hObject,evendata) %#ok<INUSD>
        close;
        FRAKTAL;
	end
%% ---------------------------------------------------------------------------
	function siguiente_boton_Callback(hObject,evendata) %#ok<INUSD>
        handles.granulado=getappdata(0,'Granulado');
        close;
        Datos_entrada_build
	end

%% ---------------------------------------------------------------------------
	function salir_boton_Callback(hObject,evendata) %#ok<INUSD>
        close all;
    end
end