function fig_hdl = version_programa_build
% VERSION_PROGRAMA_BUILD
%-------------------------------------------------------------------------------
% File name   : version_programa_build.m
%-------------------------------------------------------------------------------
 
 
% Initialize handles structure
handles = struct();
 
% Create all UI controls
build_gui();
 
% Assign function output
fig_hdl = handles.figura_version;
 
%% ---------------------------------------------------------------------------
 
% Variables
handles.granulado=getappdata(0,'Granulado');
handles.foto=getappdata(0,'foto');
handles.nfoto=getappdata(0,'nfoto');
handles.npixescala=getappdata(0,'npixescala');
handles.dpomat=getappdata(0,'dpomat');
handles.grupo=getappdata(0,'grupo');
 
 if handles.grupo==1
    set(handles.estudio_boton,'enable','off');
 end
 
 if strcmp(handles.granulado,'No')
    set(handles.version_2_panel,'visible','off');
    set(handles.delta_version_2_boton,'enable','off');
    set(handles.delta_v_2_entrada,'enable','off');
    set(handles.estudio_boton,'enable','off');
    delta=1;
 end
%% ---------------------------------------------------------------------------
    function build_gui()
% Creation of all uicontrols
 
        % --- FIGURE -------------------------------------
        handles.figura_version = figure( ...
            'Tag', 'figura_version', ...
            'Units', 'characters', ...
            'Position', [51.1 30 170 40], ...
            'Name', 'version_programa', ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Color', [0.4 0.6 1]);
        % --- PANELS -------------------------------------
        handles.version_2_panel = uipanel( ...
            'Parent', handles.figura_version, ...
            'Tag', 'version_panel', ...
            'Units', 'characters', ...
            'Position', [33 17.20769230769231 45.8 12.69230769230769], ...
            'visible', 'on', ...
            'Title', 'Coeficiente de aplastamiento', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
            'TitlePosition', 'Centertop');
 
        handles.aplastamiento_panel = uipanel( ...
            'Parent', handles.figura_version, ...
            'Tag', 'aplastamiento_panel', ...
            'Units', 'characters', ...
            'Position', [94 17.20769230769231 47 12.69230769230769], ...
            'visible', 'off', ...
            'Title', 'Estudio paramétrico', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
            'TitlePosition', 'Centertop');
        
        handles.correcciones_panel = uipanel( ...
            'Parent', handles.figura_version, ...
            'Tag', 'correcciones_panel', ...
            'Units', 'characters', ...
            'Position', [33 6 60.8 9], ...
            'visible', 'on', ...
            'Title', 'Corrección del radio de giro', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'HighlightColor', [1 0.35 0], ...
            'TitlePosition', 'Centertop');
 
        % --- STATIC TEXTS -------------------------------------
        handles.titulo_version_texto = uicontrol( ...
            'Parent', handles.figura_version, ...
            'Tag', 'titulo_version_texto', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [58.05 29.9230769230769 45.2 7.30769230769231], ...
            'FontSize', 15, ...
            'FontName', 'Candara', ...
            'Backgroundcolor', [0.4 0.6 1], ...
            'Foregroundcolor', [1 1 1],...
            'String', 'VERSIÓN 2.0');
        
        handles.inicio_aplastamiento_texto = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'inicio_aplastamiento_texto', ...
            'Style', 'text', ...
            'Units', 'characters', ...          
            'Position', [3 7.7 20.4 1.76923076923077], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'String', 'Inicio (min=1)');
        
        handles.final_aplastamiento_texto = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'final_aplastamiento_texto', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 5 25.4 1.76923076923077], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'String', 'Final (max=1.15)');
        
        handles.intervalo_aplastamiento_texto = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'intervalo_aplastamiento_texto', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [3 2.3 20.4 1.76923076923077], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'String', 'Intervalo');
        
        handles.correccion_voxel_texto = uicontrol( ...
            'Parent', handles.correcciones_panel, ...
            'Tag', 'correccion_voxel_texto', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [0 0 60 5], ...
            'visible', 'off', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0 0 0],...
            'String', 'Esta opción no está implementada para vóxeles debido a que es necesario un estudio de la corrección del radio de giro.');
 
        % --- PUSHBUTTONS -------------------------------------
        handles.atras_boton = uicontrol( ...
            'Parent', handles.figura_version, ...
            'Tag', 'atras_boton', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [94.3 1.46153846153846 22.4 2.38461538461538], ...
            'String', '< Atrás', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'Callback', @atras_boton_Callback);
 
        handles.siguiente_boton = uicontrol( ...
            'Parent', handles.figura_version, ...
            'Tag', 'siguiente_boton', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [118.7 1.46153846153846 22.4 2.38461538461538], ...
            'String', 'Siguiente >', ...
            'enable', 'off', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'Callback', @siguiente_boton_Callback);
 
        handles.salir_boton = uicontrol( ...
            'Parent', handles.figura_version, ...
            'Tag', 'salir_boton', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [144.1 1.46153846153846 22.4 2.38461538461538], ...
            'String', 'Salir', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'Callback', @salir_boton_Callback);
        
        handles.informacion_boton = uicontrol( ...
			'Parent', handles.correcciones_panel, ...
			'Tag', 'informacion_boton', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [7 5 20.2 2.07692307692308], ...
			'String', 'Información', ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [0.4 0.3 1], ...
            'Callback', @informacion_boton_Callback);
 
        % --- RADIO BUTTONS ----------------------------------------
        handles.delta_version_2_boton = uicontrol( ...
            'Parent', handles.version_2_panel, ...
            'Tag', 'delta_version_2_texto', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...          
            'Position', [3.5 7 17.4 1.76923076923077], ...
            'String', '<html>&#948; = ?</html>', ...
            'value', 1, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @delta_version_2_boton_Callback);
        
        handles.estudio_boton = uicontrol( ...
            'Parent', handles.version_2_panel, ...
            'Tag', 'estudio_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [3.5 2.2 25 3.2], ...
            'String', {'<html>Estudio paramétrico &#948;</html>'}, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @estudio_boton_Callback);
        
        handles.afirmativo_boton = uicontrol( ...
            'Parent', handles.correcciones_panel, ...
            'Tag', 'afirmativo_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [35.5 5 10 2], ...
            'String', {'Sí'}, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @afirmativo_boton_Callback);
        
        handles.negativo_boton = uicontrol( ...
            'Parent', handles.correcciones_panel, ...
            'Tag', 'negativo_boton', ...
            'Style', 'radiobutton', ...
            'Units', 'characters', ...
            'Position', [45.5 5 10 2], ...
            'String', {'No'}, ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'Foregroundcolor', [1 0.35 0],...
            'Callback', @negativo_boton_Callback);
 
        % --- EDIT TEXTS -------------------------------------
        handles.delta_v_2_entrada = uicontrol( ...
            'Parent', handles.version_2_panel, ...
            'Tag', 'delta_v_2_entrada', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [16.6 6.8 14 2], ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 12, ...
            'String', '1', ...
            'FontName', 'Candara', ...
            'enable', 'on');
        
        handles.delta_inicio_entrada = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'delta_inicio_entrada', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [26.6 7.7 14 2], ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'String', '1');
        
        handles.delta_final_entrada = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'delta_final_entrada', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [26.6 5 14 2], ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'String', '1.15');
        
        handles.delta_intervalo_entrada = uicontrol( ...
            'Parent', handles.aplastamiento_panel, ...
            'Tag', 'delta_intervalo_entrada', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [26.6 2.3 14 2], ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 12, ...
            'FontName', 'Candara', ...
            'String', '0.005');
        
        movegui(handles.figura_version,'center')
 
    end
 
%% ---------------------------------------------------------------------------
    function atras_boton_Callback(hObject,evendata) %#ok<INUSD>
        close;
        if strcmp(handles.granulado,'Si')
        Datos_imagenes_build;
        elseif strcmp(handles.granulado,'Si_voxel')
        Datos_imagenes_granuladovoxel_build;
        else
        Datos_imagenes_nogranulado_build;
        end
    end
 
%% ---------------------------------------------------------------------------
    function siguiente_boton_Callback(hObject,evendata) %#ok<INUSD>
        error=0; estudio=0; 
        handles.grupo=getappdata(0,'grupo');
        if get(handles.delta_version_2_boton,'value')==1
            handles.delta_2=str2double(get(handles.delta_v_2_entrada,'String'));
            
            if handles.delta_2<1 || handles.delta_2>(2/sqrt(3))
                dlgerror=errordlg('El valor de delta debe de estar entre 1 y 1.15','Error');            
                    kids0=findobj(dlgerror,'Type','UIControl');
                    kids1=findobj(dlgerror,'Type','Text');
 
                    % change the font and fontsize
                    extent0=get(kids1,'Extent'); % text extent in old font
                    set([kids0,kids1],'FontName','Candara','FontSize',12);
                    set(kids0,'Foregroundcolor',[0.4 0.3 1]);
                    extent1=get(kids1,'Extent'); % text extent in new font
 
                    % need to resize the msgbox object to accommodate new FontName
                    % and FontSize
                    dlgdelta=extent1-extent0; % change in extent
            
                    pos=get(kids0,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(kids0,'Position',pos); % set new position
            
                    pos=get(dlgerror,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(dlgerror,'Position',pos); % set new position
                    
                set(handles.delta_v_2_entrada,'String','NaN');
                error=1;
            end
        elseif get(handles.estudio_boton,'value')==1
            handles.delta_inicio=str2double(get(handles.delta_inicio_entrada,'String'));
            handles.delta_final=str2double(get(handles.delta_final_entrada,'String'));
            handles.delta_intervalo=str2double(get(handles.delta_intervalo_entrada,'String'));
        
            if handles.delta_inicio<1 || handles.delta_inicio>(2/sqrt(3))
                dlgerror=errordlg('El valor de delta debe de estar entre 1 y 1.15','Error');
                    kids0=findobj(dlgerror,'Type','UIControl');
                    kids1=findobj(dlgerror,'Type','Text');
 
                    % change the font and fontsize
                    extent0=get(kids1,'Extent'); % text extent in old font
                    set([kids0,kids1],'FontName','Candara','FontSize',12);
                    set(kids0,'Foregroundcolor',[0.4 0.3 1]);
                    extent1=get(kids1,'Extent'); % text extent in new font
 
                    % need to resize the msgbox object to accommodate new FontName
                    % and FontSize
                    dlgdelta=extent1-extent0; % change in extent
            
                    pos=get(kids0,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(kids0,'Position',pos); % set new position
            
                    pos=get(dlgerror,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(dlgerror,'Position',pos); % set new position
                    
                set(handles.delta_inicio_entrada,'String','NaN');
                error=1;
            elseif handles.delta_final<1 || handles.delta_final>(2/sqrt(3))
                dlgerror=errordlg('El valor de delta debe de estar entre 1 y 1.15','Error');
                    kids0=findobj(dlgerror,'Type','UIControl');
                    kids1=findobj(dlgerror,'Type','Text');
 
                    % change the font and fontsize
                    extent0=get(kids1,'Extent'); % text extent in old font
                    set([kids0,kids1],'FontName','Candara','FontSize',12);
                    set(kids0,'Foregroundcolor',[0.4 0.3 1]);
                    extent1=get(kids1,'Extent'); % text extent in new font
 
                    % need to resize the msgbox object to accommodate new FontName
                    % and FontSize
                    dlgdelta=extent1-extent0; % change in extent
            
                    pos=get(kids0,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(kids0,'Position',pos); % set new position
            
                    pos=get(dlgerror,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(dlgerror,'Position',pos); % set new position
                    
                set(handles.delta_final_entrada,'String','NaN');
                error=1;
            elseif handles.delta_final<handles.delta_inicio
                dlgerror=errordlg('El valor final de delta es menor que el inicial','Error');
                    kids0=findobj(dlgerror,'Type','UIControl');
                    kids1=findobj(dlgerror,'Type','Text');
 
                    % change the font and fontsize
                    extent0=get(kids1,'Extent'); % text extent in old font
                    set([kids0,kids1],'FontName','Candara','FontSize',12);
                    set(kids0,'Foregroundcolor',[0.4 0.3 1]);
                    extent1=get(kids1,'Extent'); % text extent in new font
 
                    % need to resize the msgbox object to accommodate new FontName
                    % and FontSize
                    dlgdelta=extent1-extent0; % change in extent
            
                    pos=get(kids0,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(kids0,'Position',pos); % set new position
            
                    pos=get(dlgerror,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(dlgerror,'Position',pos); % set new position
                    
                set(handles.delta_final_entrada,'String','NaN');
                error=1;
            elseif handles.delta_intervalo>(handles.delta_final-handles.delta_inicio)
                dlgerror=errordlg('El valor del intervalo no concuerda','Error');
                    kids0=findobj(dlgerror,'Type','UIControl');
                    kids1=findobj(dlgerror,'Type','Text');
 
                    % change the font and fontsize
                    extent0=get(kids1,'Extent'); % text extent in old font
                    set([kids0,kids1],'FontName','Candara','FontSize',12);
                    set(kids0,'Foregroundcolor',[0.4 0.3 1]);
                    extent1=get(kids1,'Extent'); % text extent in new font
 
                    % need to resize the msgbox object to accommodate new FontName
                    % and FontSize
                    dlgdelta=extent1-extent0; % change in extent
            
                    pos=get(kids0,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(kids0,'Position',pos); % set new position
            
                    pos=get(dlgerror,'Position'); % msgbox current position
                    pos=pos+dlgdelta; % change size of msgbox
                    set(dlgerror,'Position',pos); % set new position
                    
                set(handles.delta_intervalo_entrada,'String','NaN');
                error=1;
            else
            end
        end
        
       
        [a b]=size(handles.foto); % Juan Manuel: Necesario para utilizar GeneralExe2006 o GeneralExe2012
                
                
        if error==0
            col = get(handles.siguiente_boton,'backg');  % Get the background color of the figure.
            set(handles.siguiente_boton,'str','TRABAJANDO...','backg',[1 .6 .6]) % Change color of button. 
        
            pause(.01)  % FLUSH the event queue, drawnow would work too.
        
               if get(handles.delta_version_2_boton,'value')==1
                    handles.version={'2'}; setappdata(0,'version',handles.version);
                    if b>1 % Cambio Juan Manuel
                        handles.dfmat={GeneralExe2012grupo(handles.foto,handles.nfoto,handles.npixescala,handles.dpomat,handles.grupo,handles.delta_2)};
                    else
                        handles.dfmat={GeneralExe2012individual(handles.foto,handles.nfoto,handles.npixescala,handles.dpomat,handles.grupo,handles.delta_2)};
                    end
                elseif get(handles.estudio_boton,'value')==1
                    handles.version={'2'}; setappdata(0,'version',handles.version);
                    handles.dfmat=[];
                    
                    setappdata(0,'delta_inicio',handles.delta_inicio);
                    setappdata(0,'delta_fin',handles.delta_final);
                    setappdata(0,'delta_intervalo',handles.delta_intervalo);
                    %había fallo
                    for delta=handles.delta_inicio:handles.delta_intervalo:handles.delta_final
                        dfmat2=GeneralExe2012individual(handles.foto,handles.nfoto,handles.npixescala,handles.dpomat,handles.grupo,delta);
                        handles.dfmat=[handles.dfmat;dfmat2];
                        estudio=1;
                    end
                    handles.dfmat={handles.dfmat};
                end
              
            setappdata(0,'dfmat',handles.dfmat);
            setappdata(0,'estudio',estudio);
        
            set(handles.siguiente_boton,'String','Tomar datos','backg',col)  % Now reset the button features.
            
%             figure; A=cell2mat(handles.dfmat{1}(:,8)); B=cell2mat(handles.dfmat{1}(:,10)); 
%             plot(A,B,'-')
            close;
            salida_build;
          
        end
    end
 
%% ---------------------------------------------------------------------------
    function salir_boton_Callback(hObject,evendata) %#ok<INUSD>
        app=getappdata(0); %get all the appdata of 0
        %and then
        appdatas = fieldnames(app);
        for kA = 1:length(appdatas)
            rmappdata(0,appdatas{kA});
        end
        close all;
    end
  
%% ---------------------------------------------------------------------------
	function informacion_boton_Callback(hObject,evendata) %#ok<INUSD>
        informacion_build
	end
%% ---------------------------------------------------------------------------
    function delta_version_2_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.estudio_boton,'value')==1
            set(handles.delta_v_2_entrada,'enable','on');
            set(handles.estudio_boton,'value',0);
            set(handles.aplastamiento_panel,'visible','off');
            
        elseif get(handles.delta_version_2_boton,'value')==0
            set(handles.delta_v_2_entrada,'enable','off');
            set(handles.estudio_boton,'value',0);
            set(handles.aplastamiento_panel,'visible','off');
        else        
            set(handles.delta_v_2_entrada,'enable','on');
            set(handles.estudio_boton,'value',0);
            set(handles.aplastamiento_panel,'visible','off');
        end
    end
 
%% ---------------------------------------------------------------------------
    function estudio_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.delta_version_2_boton,'value')==1
            set(handles.delta_version_2_boton,'value',0);
            set(handles.delta_v_2_entrada,'enable','off');            
            set(handles.aplastamiento_panel,'visible','on');
        elseif get(handles.estudio_boton,'value')==0
            set(handles.delta_v_2_entrada,'enable','off');
            set(handles.estudio_boton,'value',0);
            set(handles.aplastamiento_panel,'visible','off');
        else        
            set(handles.delta_version_2_boton,'value',0);
            set(handles.delta_v_2_entrada,'enable','off');            
            set(handles.aplastamiento_panel,'visible','on');
        end
    end
 
%% ---------------------------------------------------------------------------
    function afirmativo_boton_Callback(hObject,evendata) %#ok<INUSD>
        if strcmp(handles.granulado,'Si_voxel') || strcmp(handles.granulado,'No')
            if get(handles.negativo_boton,'value')==1
            set(handles.negativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','off');
            set(handles.correccion_voxel_texto,'visible','on');
        elseif get(handles.afirmativo_boton,'value')==0
            set(handles.afirmativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','off');
            set(handles.correccion_voxel_texto,'visible','off');
        else        
            set(handles.negativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','off');
            set(handles.correccion_voxel_texto,'visible','on');
            end
        else
            if get(handles.negativo_boton,'value')==1
            set(handles.negativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','on');
            set(handles.correccion_voxel_texto,'visible','off');
        elseif get(handles.afirmativo_boton,'value')==0
            set(handles.afirmativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','off');
            set(handles.correccion_voxel_texto,'visible','off');
        else        
            set(handles.negativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','on');
            set(handles.correccion_voxel_texto,'visible','off');
            end
        setappdata(0,'Correccion','Si');
        end
    end

%% ---------------------------------------------------------------------------
    function negativo_boton_Callback(hObject,evendata) %#ok<INUSD>
        if get(handles.afirmativo_boton,'value')==1
            set(handles.afirmativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','on');
            set(handles.correccion_voxel_texto,'visible','off');
        elseif get(handles.negativo_boton,'value')==0
            set(handles.negativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','off');
            set(handles.correccion_voxel_texto,'visible','off');
        else        
            set(handles.afirmativo_boton,'value',0);
            set(handles.siguiente_boton,'enable','on');
            set(handles.correccion_voxel_texto,'visible','off');
        end
        setappdata(0,'Correccion','No');
    end
end