# Generated by Django 6.0.2 on 2026-02-27 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('groq', 'Groq'), ('xai', 'xAI (Grok)')], default='anthropic', max_length=20)),
                ('api_key_encrypted', models.TextField(help_text='Fernet-encrypted API key')),
                ('model_name', models.CharField(default='claude-sonnet-4-20250514', help_text='Model name to use (e.g., claude-sonnet-4-20250514, gpt-4o)', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Use this provider by default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
