# Generated by Django 5.2.11 on 2026-02-27 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ai_access', models.BooleanField(default=False, help_text='Whether this user can access AI assistant features')),
                ('access_granted_at', models.DateTimeField(blank=True, help_text='When AI access was granted', null=True)),
                ('notes', models.TextField(blank=True, help_text="Admin notes about this user's AI access")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_granted_by', models.ForeignKey(blank=True, help_text='Admin who granted AI access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_access_granted_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI User Profile',
                'verbose_name_plural': 'AI User Profiles',
            },
        ),
    ]
