# Generated by Django 6.0.2 on 2026-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_conversation_chatmessage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='available_models',
            field=models.JSONField(blank=True, default=list, help_text='Cached list of models available from this provider'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='models_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='When the model catalog was last refreshed', null=True),
        ),
    ]
