# Generated by Django 5.2.11 on 2026-02-17 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.BinaryField(help_text='Original uploaded image')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_content_type', models.CharField(max_length=50)),
                ('processed_image', models.BinaryField(blank=True, help_text='Binarized/preprocessed image', null=True)),
                ('preprocessing_params', models.JSONField(help_text='Threshold method, invert, clean params')),
                ('method', models.CharField(choices=[('box_counting', 'Box-Counting'), ('sandbox', 'Sandbox Method'), ('correlation', 'Correlation Dimension'), ('lacunarity', 'Lacunarity'), ('multifractal', 'Multifractal Dq')], max_length=20)),
                ('method_params', models.JSONField(blank=True, help_text='Method-specific parameters', null=True)),
                ('results', models.JSONField(blank=True, help_text='Fractal dimension, R2, log data, etc.', null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Image analyses',
                'db_table': 'image_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sets', to='projects.project')),
                ('simulations', models.ManyToManyField(blank=True, related_name='comparison_sets', to='simulations.simulation')),
                ('analyses', models.ManyToManyField(blank=True, related_name='comparison_sets', to='fractal_analysis.imageanalysis')),
            ],
            options={
                'db_table': 'comparison_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['project', '-created_at'], name='image_analy_project_1e40c6_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['status'], name='image_analy_status_76cf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['method'], name='image_analy_method_7a3693_idx'),
        ),
    ]
