# Generated by Django 6.0.2 on 2026-02-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fractal_analysis', '0002_add_fraktal_analysis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fraktalanalysis',
            new_name='fraktal_ana_project_e0af13_idx',
            old_name='fraktal_ana_project_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='fraktalanalysis',
            new_name='fraktal_ana_status_61ae1f_idx',
            old_name='fraktal_ana_status_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='fraktalanalysis',
            new_name='fraktal_ana_model_1f978d_idx',
            old_name='fraktal_ana_model_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='fraktalanalysis',
            new_name='fraktal_ana_source__fe2d97_idx',
            old_name='fraktal_ana_source__j0k1l2_idx',
        ),
    ]
