# Generated by Django 6.0.2 on 2026-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractal_analysis', '0003_rename_fraktal_ana_project_a1b2c3_idx_fraktal_ana_project_e0af13_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraktalanalysis',
            name='auto_calibrate',
            field=models.BooleanField(default=False, help_text='Automatically find optimal dpo by testing multiple values'),
        ),
    ]
