# Generated by Django 6.0.2 on 2026-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractal_analysis', '0004_add_auto_calibrate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraktalanalysis',
            name='name',
            field=models.CharField(blank=True, help_text='Optional display name. Auto-generated if not provided.', max_length=255),
        ),
    ]
