# Generated by Django 6.0.2 on 2026-04-27 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractal_analysis', '0005_add_fraktal_name'),
        ('projects', '0002_add_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraktalBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=32)),
                ('calibration_source', models.CharField(max_length=16)),
                ('pixels_per_100nm', models.FloatField()),
                ('dpo_used', models.FloatField()),
                ('autocalibrate_source', models.CharField(blank=True, max_length=16, null=True)),
                ('autocalibrate_image_index', models.IntegerField(blank=True, null=True)),
                ('sim_id', models.UUIDField(blank=True, null=True)),
                ('n_images', models.IntegerField(default=0)),
                ('n_successful', models.IntegerField(default=0)),
                ('mean_df', models.FloatField(blank=True, null=True)),
                ('std_df', models.FloatField(blank=True, null=True)),
                ('median_df', models.FloatField(blank=True, null=True)),
                ('min_df', models.FloatField(blank=True, null=True)),
                ('max_df', models.FloatField(blank=True, null=True)),
                ('original_zip_filename', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraktal_batches', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraktal_batches', to='projects.project')),
            ],
            options={
                'db_table': 'fraktal_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraktalBatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('fractal_dimension', models.FloatField(blank=True, null=True)),
                ('prefactor', models.FloatField(blank=True, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('n_particles_counted', models.IntegerField(blank=True, null=True)),
                ('dpo_used', models.FloatField()),
                ('error', models.TextField(blank=True)),
                ('image_png', models.BinaryField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fractal_analysis.fraktalbatch')),
            ],
            options={
                'db_table': 'fraktal_batch_images',
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='fraktalbatch',
            index=models.Index(fields=['project', '-created_at'], name='fraktal_bat_project_3664a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fraktalbatchimage',
            unique_together={('batch', 'index')},
        ),
    ]
