# Generated by Django 6.0.2 on 2026-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractal_analysis', '0006_fraktal_batch_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraktalbatchimage',
            name='png_scientific_bytes',
            field=models.BinaryField(blank=True, null=True, verbose_name='Scientific PNG bytes'),
        ),
    ]
