# Generated by Django 5.2.11 on 2026-02-17 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Aggregation'), ('tunable', 'Tunable Sticking Probability')], max_length=20)),
                ('parameters', models.JSONField(help_text='Algorithm-specific parameters (n_particles, sticking_probability, etc.)')),
                ('seed', models.BigIntegerField(help_text='Random seed for reproducibility')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('geometry', models.BinaryField(blank=True, help_text='NumPy array of particle coordinates and radii', null=True)),
                ('metrics', models.JSONField(blank=True, help_text='Computed metrics: Df, kf, Rg, porosity, coordination, RDF', null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='projects.project')),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametricStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_algorithm', models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Aggregation'), ('tunable', 'Tunable Sticking Probability')], max_length=20)),
                ('base_parameters', models.JSONField(help_text='Fixed parameters for all simulations')),
                ('parameter_grid', models.JSONField(help_text='Parameters to vary: {param_name: [values]}')),
                ('seeds_per_combination', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='projects.project')),
                ('simulations', models.ManyToManyField(blank=True, related_name='studies', to='simulations.simulation')),
            ],
            options={
                'verbose_name_plural': 'Parametric studies',
                'db_table': 'parametric_studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['project', '-created_at'], name='simulations_project_cbf7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['status'], name='simulations_status_d36fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['algorithm'], name='simulations_algorit_913a20_idx'),
        ),
    ]
