# Generated by Django 6.0.2 on 2026-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=50),
        ),
    ]
