# Generated by Django 6.0.2 on 2026-02-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_add_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametricstudy',
            name='base_algorithm',
            field=models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Particle-Cluster'), ('ballistic_cc', 'Ballistic Cluster-Cluster'), ('tunable', 'Tunable Sticking Probability')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='algorithm',
            field=models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Particle-Cluster'), ('ballistic_cc', 'Ballistic Cluster-Cluster'), ('tunable', 'Tunable Sticking Probability')], max_length=20),
        ),
    ]
