# Generated by Django 6.0.2 on 2026-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_add_ballistic_cc_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricstudy',
            name='box_counting_params',
            field=models.JSONField(blank=True, help_text="Box-counting params: {'points_per_sphere': 100, 'precision': 18}", null=True),
        ),
        migrations.AddField(
            model_name='parametricstudy',
            name='include_box_counting',
            field=models.BooleanField(default=False, help_text='Run box-counting analysis after each simulation completes'),
        ),
        migrations.AddField(
            model_name='parametricstudy',
            name='include_limiting_cases',
            field=models.BooleanField(default=False, help_text='Include theoretical extreme parameter combinations'),
        ),
        migrations.AddField(
            model_name='parametricstudy',
            name='limiting_cases_config',
            field=models.JSONField(blank=True, help_text="Configuration: {'include_boundaries': true, 'include_theoretical': true, ...}", null=True),
        ),
        migrations.AddField(
            model_name='parametricstudy',
            name='sintering_config',
            field=models.JSONField(blank=True, help_text="Sintering params: {'distribution_type': 'fixed'|'uniform'|'normal', ...}", null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.CharField(blank=True, help_text='Optional display name. Auto-generated if not provided.', max_length=255),
        ),
        migrations.AlterField(
            model_name='parametricstudy',
            name='base_algorithm',
            field=models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Particle-Cluster'), ('ballistic_cc', 'Ballistic Cluster-Cluster'), ('tunable', 'Tunable Sticking Probability'), ('tunable_cc', 'Tunable Cluster-Cluster'), ('limiting', 'Limiting Case Geometry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='algorithm',
            field=models.CharField(choices=[('dla', 'Diffusion-Limited Aggregation'), ('cca', 'Cluster-Cluster Aggregation'), ('ballistic', 'Ballistic Particle-Cluster'), ('ballistic_cc', 'Ballistic Cluster-Cluster'), ('tunable', 'Tunable Sticking Probability'), ('tunable_cc', 'Tunable Cluster-Cluster'), ('limiting', 'Limiting Case Geometry')], max_length=20),
        ),
    ]
